version: "3"
services:
  app:
    image: pudding/docker-web:docker-web-apache-solr-app-20250202.211341
    tty: true
    ports:
      - "8080:8080"
    environment:
      - LOCAL_VOLUMN_PATH=/data
      - APP_NAME="File Browser"
      - CONTAINER_NAME=docker-web-apache-solr-app
      - URL_TO_TEST_READY=http://127.0.0.1:8080/
    volumes: 
      - "__SOURCE__/data:/data"