# Only for local testing
version: "3"
services:
  app:
    build: 
      context: ./../
      dockerfile: ./app-build/Dockerfile
    tty: true
    #user: solr
    ports:
      # @TODO
      - "8081:8081"
    environment:
      - RUN_IN_LOCAL=true
    volumes: 
      # @TODO
      - "./../data:/data"