# Only for local testing
version: "3"
services:
  app:
    build: 
      context: ./../
      dockerfile: ./app-build/Dockerfile
    tty: true
    # command: ["bash"]
    ports:
      # WEBAPP_PORT不可以使用8080
      - "8081:8081"
    volumes: 
      - "./data:/data"
    environment:
      - RUN_IN_LOCAL=false

    ## For Nvidia GPU's
    # deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]