version: "3"
services:
  app:
    container_name: colab-file-browser
    image: pudding/docker-web:colab-file-browser-20250204.204856
    tty: true
    # command: ["bash"]
    ports:
      # WEBAPP_PORT不可以使用8080
      - "8081:8081"
    volumes: 
      - "./data:/data"

    ## For Nvidia GPU's
    # deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]