FROM pudding/docker-app-filebrowse-20230822-1557

# =================================================================
# Configuration (don't remove)

# The path to save data
ENV APP_NAME="File Browser"
ENV LOCAL_VOLUMN_PATH=/data/
ENV URL_TO_TEST_READY=http://127.0.0.1:8080/

ENV LOCAL_PORT=8080


ENTRYPOINT []
CMD ["bash", "/startup.sh"]
