version: "3"
services:
  app:
    container_name: colab-file-browser
    image: pudding/docker-web:colab-file-browser-20250202.220343
    tty: true
    ports:
      # WEBAPP_PORT不可以使用8080
      - "8081:8081"
    environment:
      - LOCAL_VOLUMN_PATH=/data
      - APP_NAME="File Browser"
      - URL_TO_TEST_READY=http://127.0.0.1:8081/
    volumes: 
      - "__SOURCE__/data:/data"