version: "3"
services:
  app:
    container_name: colab-file-browser
    image: pudding/docker-web:colab-file-browser-20250202.212107
    tty: true
    ports:
      - "8080:8080"
    environment:
      - LOCAL_VOLUMN_PATH=/data
      - APP_NAME="File Browser"
      - URL_TO_TEST_READY=http://127.0.0.1:8080/
    volumes: 
      - "__SOURCE__/data:/data"